benchmark:
  name: "ruler"
  framework: "lm_eval"

vllm_overrides:
  max_num_seqs: 16

evaluation:
  tasks: "ruler"
  batch_size: 16
  max_seq_lengths:
    - 4096
    - 8192
    - 16384
    - 32768
    - 65536
    - 131072

output:
  dir: "results/evaluations/llm/ruler"
