model:
  name: "Qwen/Qwen3-8B"
  dtype: "bfloat16"
  temperature: 0.0
  enable_thinking: false

server:
  base_url: "http://0.0.0.0:8000/v1"
  api_key: "dummy"

metadata:
  family: "qwen_3"
  provider: "alibaba"
  params_billion: 8.0
  architecture: "dense"
